events {
    worker_connections 4096;
}

http {
    # Tell nginx to use docker DNS (127.0.0.11)
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;
    keepalive_timeout 30;
    send_timeout 30;

    server {
        listen 5000;

        location / {
            set $web_backend web:5000;
            proxy_pass http://$web_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
